# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Homless Continuous Integration AOT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Required Dependencies Triggers
      run: npm install
    - name: Linting All Code
      run: npm run lint
    - name: Building to Production
      run: npm run build -- --prod --aot
    - name: Testing HomLess
      run: npm test --

